name: MCP hub Build and Push
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      mcp:
        description: 'MCP to import'
env:
  REGISTRY: ghcr.io
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.23.3'
      - name: Install dependencies
        run: go get .
      - name: Validate hub
        run: go run main.go validate -c hub.yaml
      - name: Build and push
        if: inputs.approve == ''
        run: go run main.go import -c hub.yaml -p -r ${{ env.REGISTRY }}/${{ github.repository }}
      - name: Build and push
        if: inputs.approve != ''
        run: go run main.go import -c hub.yaml -p -r ${{ env.REGISTRY }}/${{ github.repository }} -m ${{ inputs.mcp }}
